"""add constituency

Revision ID: 3aae7d649d94
Revises: cfe4c5acef27
Create Date: 2020-08-30 15:01:20.017478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aae7d649d94'
down_revision = 'cfe4c5acef27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('constituency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'constituency')
    # ### end Alembic commands ###
