"""added more content on profile page

Revision ID: 92664e60bf44
Revises: 2b9b725146de
Create Date: 2020-08-29 16:27:44.251551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92664e60bf44'
down_revision = '2b9b725146de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('representative', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'representative')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
