"""hello

Revision ID: f859c242b53d
Revises: 83d584c1b31d
Create Date: 2020-09-02 14:40:24.214621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f859c242b53d'
down_revision = '83d584c1b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paragraph_order_id', table_name='paragraph')
    op.drop_table('paragraph')
    op.add_column('speech', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speech', 'body')
    op.create_table('paragraph',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('speech_id', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.VARCHAR(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['speech_id'], ['speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paragraph_order_id', 'paragraph', ['order_id'], unique=False)
    # ### end Alembic commands ###
